# Generated by Django 5.1.2 on 2024-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
    ]
