# Generated by Django 5.1.2 on 2024-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_student_weighted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='weighted_score',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
